redirects:
  projects: about-me/projects
  talks: about-me/talks
  blog/challenges-in-full-text-search: software-engineering/challenges-in-full-text-search.md 
  blog/how-to-be-productive: life/how-to-be-productive.md 
  blog/go-to-guide-to-run-communities: community/go-to-guide-to-run-communities.md 
  blog/emails-alerts-airflow-with-sendgrid: apache-airflow/emails-alerts-airflow-with-sendgrid.md 
  blog/what-happens-during-docker-build-and-run: devops/what-happens-during-docker-build-and-run.md 
  blog/docker-introduction: devops/docker-introduction.md 
  blog/the-ideal-team-player-book-review: book-notes/the-ideal-team-player-book-review.md 
  blog/a-world-where-women-in-tech-rules: community/a-world-where-women-in-tech-rules.md 
  blog/generate-uml-diagrams-from-python-code: python/generate-uml-diagrams-from-python-code.md 
  blog/david-and-Goliath-book-summary: book-notes/david-and-Goliath-book-summary.md 
  blog/deploying-airflow-on-kubernetes: apache-airflow/deploying-airflow-on-kubernetes.md 
  blog/merge-python-module-script: python/merge-python-module-script.md 
  blog/apache-airflow-introduction: apache-airflow/apache-airflow-introduction.md 
  blog/atomic-habits-book-summary: book-notes/atomic-habits-book-summary.md 
  blog/the-magic-of-responsiblity: life/the-magic-of-responsiblity.md 
  blog/kubernetes-101-deploy-apps-in-kubernetes: devops/kubernetes-101-deploy-apps-in-kubernetes.md 
  blog/seven-habits-book-summary: book-notes/seven-habits-book-summary.md 
  blog/sending-emails-from-airflow: apache-airflow/sending-emails-from-airflow.md 
  blog/building-own-flask-1: python/web/flask/building-own-flask-1.md 
  blog/it-doesn't-have-to-be-crazy-at-work: book-notes/it-doesn't-have-to-be-crazy-at-work.md 
  blog/shopping-like-a-minimalist: life/shopping-like-a-minimalist.md 
  blog/airflow-operators-comparison: apache-airflow/airflow-operators-comparison.md 
  blog/learning-golang: golang/learning-golang.md 
  blog/the-git-problem: software-engineering/git-and-github/the-git-problem.md 
  blog/secrets-as-python-file: python/secrets-as-python-file.md 
  blog/asynchronous-task-execution-in-python: python/asynchronous-task-execution-in-python.md 
  blog/backend-engineer-behind-the-scenes: software-engineering/backend-engineer-behind-the-scenes.md 
  blog/authentication-in-python: python/authentication-in-python.md 
  blog/why-should-you-attend-tech-conferences: community/why-should-you-attend-tech-conferences.md 
  blog/the-beauty-of-your-brain: book-notes/the-beauty-of-your-brain.md 
  blog/how-to-set-goals: life/how-to-set-goals.md 
  blog/custom-oauth2-with-auth0: software-engineering/custom-oauth2-with-auth0.md 
  blog/docker-virtualization-vs-containerization: devops/docker-virtualization-vs-containerization.md 
  blog/5-reasons-why-you-should-start-your-fitness-routineasap: life/5-reasons-why-you-should-start-your-fitness-routineasap.md 
  blog/caching-in-python: python/caching-in-python.md 
