redirects:
  blog/challenges-in-full-text-search: "software-engineering/Challenges In Full-Text-Search Systems.md" 
  blog/how-to-be-productive: "life/How to be (more) Productive?.md" 
  blog/go-to-guide-to-run-communities: "community/A Go to Guide to Run a Community.md" 
  blog/emails-alerts-airflow-with-sendgrid: "apache-airflow/Sending Email Alerts in Apache Airflow with Sendgrid.md" 
  blog/what-happens-during-docker-build-and-run: "devops/What Happens During Docker Build and Run?.md" 
  blog/docker-introduction: "devops/Introduction to Docker - The What, Why and How.md" 
  blog/the-ideal-team-player-book-review: "book-notes/Are you an Ideal Team Player?.md" 
  blog/a-world-where-women-in-tech-rules: "community/A World Where WomenInTech Rules.md" 
  blog/generate-uml-diagrams-from-python-code: "python/How to Generate UML Diagrams from Python Source Code?.md" 
  blog/david-and-Goliath-book-summary: "book-notes/David and Goliath Book Summary.md" 
  blog/deploying-airflow-on-kubernetes: "apache-airflow/How to Set up Airflow on Kubernetes?.md" 
  blog/merge-python-module-script: "python/Merging Python Modules.md" 
  blog/apache-airflow-introduction: "apache-airflow/An Introduction to Apache Airflow.md" 
  blog/atomic-habits-book-summary: "book-notes/Atomic Habits Book Summary.md" 
  blog/the-magic-of-responsiblity: "life/The Magic of Responsibility — A Story.md" 
  blog/kubernetes-101-deploy-apps-in-kubernetes: "devops/Deploying Flask Applications in Kubernetes (Digitalocean).md" 
  blog/seven-habits-book-summary: "book-notes/7 Habits of Highly Effective People - Book Summary.md" 
  blog/sending-emails-from-airflow: "apache-airflow/How to Send Email Alerts from Airflow?.md" 
  blog/building-own-flask-1: "python/web/flask/Building OwnFlask - A Flask(like) Python Framework.md" 
  blog/it-doesn't-have-to-be-crazy-at-work: "book-notes/It Doesn't Have to be Crazy at Work.md" 
  blog/shopping-like-a-minimalist: "life/Shopping Like a Stingy-Minimalist.md" 
  blog/airflow-operators-comparison: "apache-airflow/Airflow Operators - A Comparison.md" 
  blog/learning-golang: "golang/How I Wrote my 1st 100 Lines of Golang Code.md" 
  blog/the-git-problem: "software-engineering/git-and-github/How I Got Out of a Knee Deep Git Problem.md" 
  blog/secrets-as-python-file: "python/Are your Secrets Safe In Python?.md" 
  blog/asynchronous-task-execution-in-python: "python/Asynchronous Task Execution In Python.md" 
  blog/backend-engineer-behind-the-scenes: "software-engineering/Backend Engineer - Behind the Scenes.md" 
  blog/authentication-in-python: "python/All About Authentication Systems.md" 
  blog/why-should-you-attend-tech-conferences: "community/Why Should you Attend Tech Conferences?.md" 
  blog/the-beauty-of-your-brain: "book-notes/The Beauty of Your Brain.md" 
  blog/how-to-set-goals: "life/End Goal - How to set goals and track them?.md" 
  blog/custom-oauth2-with-auth0: "software-engineering/How to Connect to Custom Oauth2 Provider Using Auth0?.md" 
  blog/docker-virtualization-vs-containerization: "devops/Docker - Virtualization vs Containerization.md" 
  blog/5-reasons-why-you-should-start-your-fitness-routineasap: "life/5 Reasons Why You Should Start your Fitness Routine ASAP?.md" 
  blog/caching-in-python: "python/Caching in Python.md" 
